import { BUILDINGS_IMAGES } from './images';

import type { Building } from 'src/types';

export const BUILDINGS_LIST: Building[] = [
  {
    id: 'bd_1_default',
    image: BUILDINGS_IMAGES.bd_1,
    isOpen: true,
    isBuilding: false,
    price: 0,
    timeToBuild: 0,
  },
  {
    id: 'bd_2',
    image: BUILDINGS_IMAGES.bd_2,
    isOpen: false,
    isBuilding: false,
    price: 25,
    timeToBuild: 300000,
  },
  {
    id: 'bd_3',
    image: BUILDINGS_IMAGES.bd_3,
    isOpen: false,
    isBuilding: false,
    price: 35,
    timeToBuild: 350000,
  },
  {
    id: 'bd_4',
    image: BUILDINGS_IMAGES.bd_4,
    isOpen: false,
    isBuilding: false,
    price: 45,
    timeToBuild: 400000,
  },
  {
    id: 'bd_5',
    image: BUILDINGS_IMAGES.bd_5,
    isOpen: false,
    isBuilding: false,
    price: 55,
    timeToBuild: 444444,
  },
  {
    id: 'bd_6',
    image: BUILDINGS_IMAGES.bd_6,
    isOpen: false,
    isBuilding: false,
    price: 65,
    timeToBuild: 500000,
  },
  {
    id: 'bd_7',
    image: BUILDINGS_IMAGES.bd_7,
    isOpen: false,
    isBuilding: false,
    price: 75,
    timeToBuild: 500000,
  },
  {
    id: 'bd_8',
    image: BUILDINGS_IMAGES.bd_8,
    isOpen: false,
    isBuilding: false,
    price: 85,
    timeToBuild: 500000,
  },
  {
    id: 'bd_9',
    image: BUILDINGS_IMAGES.bd_9,
    isOpen: false,
    isBuilding: false,
    price: 95,
    timeToBuild: 550000,
  },
  {
    id: 'bd_10',
    image: BUILDINGS_IMAGES.bd_10,
    isOpen: false,
    isBuilding: false,
    price: 100,
    timeToBuild: 550000,
  },
  {
    id: 'bd_11',
    image: BUILDINGS_IMAGES.bd_11,
    isOpen: false,
    isBuilding: false,
    price: 115,
    timeToBuild: 600000,
  },
  {
    id: 'bd_12',
    image: BUILDINGS_IMAGES.bd_12,
    isOpen: false,
    isBuilding: false,
    price: 120,
    timeToBuild: 650000,
  },
];
